<script setup lang="ts">
import type { DashboardSummary } from '@/api/dashboard'
defineProps<{ summary: DashboardSummary; loading: boolean }>()
function statusDotClass(status: string): string { return status === 'ONLINE' ? 'bg-emerald-500' : status === 'IDLE' ? 'bg-amber-500' : 'bg-slate-400' }
</script>

<template>
  <div class="space-y-7"><div class="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><div v-for="card in [{ label: '进行中工单', value: summary.activeOrders, unit: '单', color: 'indigo' }, { label: '在线设备', value: summary.onlineDevices, unit: '台', color: 'emerald' }, { label: '今日产量', value: summary.todayOutput, unit: '件', color: 'amber' }, { label: '一次合格率', value: summary.qualityRate, unit: '%', color: 'violet' }]" :key="card.label" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">{{ card.label }}</p><div class="mt-3 flex items-end gap-2"><span class="text-3xl font-bold" :class="`text-${card.color}-600`">{{ loading ? '—' : card.value }}</span><span class="mb-1 text-sm text-slate-400">{{ card.unit }}</span></div><div class="mt-4 h-1.5 rounded-full bg-slate-100"><div class="h-1.5 w-3/4 rounded-full" :class="`bg-${card.color}-500`"></div></div></div></div><div class="grid gap-6 xl:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-6 xl:col-span-2"><h2 class="font-bold">生产节拍</h2><p class="mt-1 text-sm text-slate-400">今日各时段完成数量</p><div class="mt-8 flex h-48 items-end gap-3 border-b border-slate-100 px-3"><div v-for="(height, index) in [35, 55, 45, 72, 63, 88, 76, 94, 68, 82, 73, 90]" :key="index" class="group flex flex-1 flex-col items-center gap-2"><div class="w-full rounded-t-md bg-indigo-500" :style="{ height: `${height}%` }"></div><span class="text-[10px] text-slate-400">{{ index + 8 }}:00</span></div></div></div><div class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="font-bold">设备状态</h2><div v-if="summary.devices?.length" class="mt-6 space-y-5"><div v-for="device in (summary.devices ?? [])" :key="device.id" class="flex items-center justify-between"><div class="flex items-center gap-3"><span class="h-2.5 w-2.5 rounded-full" :class="statusDotClass(device.status)"></span><span class="text-sm">{{ device.name }} <span class="text-xs text-slate-400">{{ device.code }}</span></span></div><span class="text-xs text-slate-400">{{ device.status }}</span></div></div><p v-else class="mt-6 text-sm text-slate-400">暂无设备数据，请先创建设备。</p></div></div></div>
</template>
