<script setup lang="ts">
import type { DashboardSummary } from '@/api/dashboard'
defineProps<{ summary: DashboardSummary; loading: boolean }>()
function statusColor(status: string): 'success' | 'warning' | 'neutral' { return status === 'ONLINE' ? 'success' : status === 'IDLE' ? 'warning' : 'neutral' }
</script>

<template>
  <div class="space-y-7">
    <section class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-medium text-primary">运营概览</p><h2 class="mt-1 text-2xl font-semibold tracking-tight text-slate-800">今天，生产运行得怎么样？</h2><p class="mt-2 text-sm text-slate-500">查看当前制造现场的关键指标和设备状态。</p></div><div class="rounded-xl bg-white/62 px-3 py-2 text-xs text-slate-500">数据范围：今日实时</div></section>
    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <UCard v-for="card in [{ label: '进行中工单', value: summary.activeOrders, unit: '单', icon: 'assignment', tone: 'primary' }, { label: '在线设备', value: summary.onlineDevices, unit: '台', icon: 'precision_manufacturing', tone: 'success' }, { label: '今日产量', value: summary.todayOutput, unit: '件', icon: 'inventory_2', tone: 'warning' }, { label: '一次合格率', value: summary.qualityRate, unit: '%', icon: 'verified', tone: 'secondary' }]" :key="card.label" class="mes-card"><div class="flex items-start justify-between"><div><p class="text-sm text-slate-500">{{ card.label }}</p><div class="mt-3 flex items-baseline gap-2"><span class="text-3xl font-semibold tracking-tight text-slate-800">{{ loading ? '—' : card.value }}</span><span class="text-sm text-slate-400">{{ card.unit }}</span></div></div><span :class="['mes-tone-' + card.tone, 'grid h-9 w-9 place-items-center rounded-xl']"><span class="material-symbols-rounded text-[20px]">{{ card.icon }}</span></span></div><UProgress class="mt-5" :color="card.tone" :model-value="loading ? 0 : 75" /></UCard>
    </section>
    <section class="grid gap-5 xl:grid-cols-[1.35fr_0.65fr]">
      <UCard class="mes-card"><template #header><div class="flex items-center justify-between"><div><h3 class="font-semibold text-slate-800">生产节拍</h3><p class="mt-1 text-xs text-slate-500">今日各时段完成数量</p></div><span class="rounded-lg bg-primary-50 px-2.5 py-1 text-xs text-primary">每小时</span></div></template><div class="flex h-56 items-end gap-2 rounded-2xl bg-[#edf5f9] px-4 pb-3 pt-6 sm:gap-3"><div v-for="(height, index) in [35, 55, 45, 72, 63, 88, 76, 94, 68, 82, 73, 90]" :key="index" class="flex flex-1 flex-col items-center gap-2"><div class="w-full rounded-t-lg bg-primary/75 shadow-[0_6px_12px_rgb(85_125_159/0.14)]" :style="{ height: height + '%' }"></div><span class="text-[10px] text-slate-400">{{ index + 8 }}:00</span></div></div></UCard>
      <UCard class="mes-card"><template #header><div class="flex items-center justify-between"><h3 class="font-semibold text-slate-800">设备状态</h3><span class="text-xs text-slate-400">{{ summary.devices?.length ?? 0 }} 台设备</span></div></template><div v-if="summary.devices?.length" class="space-y-2.5"><div v-for="device in (summary.devices ?? [])" :key="device.id" class="flex items-center justify-between rounded-xl bg-[#edf5f8] px-3 py-3"><div><p class="text-sm font-medium text-slate-700">{{ device.name }}</p><p class="mt-0.5 text-xs text-slate-400">{{ device.code }}</p></div><UBadge :color="statusColor(device.status)" variant="subtle">{{ device.status }}</UBadge></div></div><UAlert v-else color="neutral" variant="subtle" title="暂无设备数据，请先创建设备。" /></UCard>
    </section>
    <section class="grid gap-5 lg:grid-cols-3"><UCard class="mes-card lg:col-span-2"><template #header><div><h3 class="font-semibold text-slate-800">运营提示</h3><p class="mt-1 text-xs text-slate-500">让团队快速知道下一步该关注什么</p></div></template><div class="grid gap-3 sm:grid-cols-3"><div class="rounded-2xl bg-[#edf5f8] p-4"><p class="text-xs font-medium text-primary">生产</p><p class="mt-2 text-sm leading-6 text-slate-600">保持节拍稳定，关注当前进行中的工单。</p></div><div class="rounded-2xl bg-[#eef6f3] p-4"><p class="text-xs font-medium text-emerald-700">设备</p><p class="mt-2 text-sm leading-6 text-slate-600">优先处理离线或待维护设备。</p></div><div class="rounded-2xl bg-[#f7f3ea] p-4"><p class="text-xs font-medium text-amber-700">审批</p><p class="mt-2 text-sm leading-6 text-slate-600">及时查看待处理的变更申请。</p></div></div></UCard><UCard class="mes-card"><template #header><h3 class="font-semibold text-slate-800">工作台说明</h3></template><p class="text-sm leading-7 text-slate-500">这里聚合生产执行、设备管理和审批协作信息，帮助你快速进入当前最重要的工作。</p></UCard></section>
  </div>
</template>
