<script setup lang="ts">
import { computed, h, onMounted, ref } from 'vue'
import UButton from '@nuxt/ui/components/Button.vue'
import type { TableColumn } from '@nuxt/ui'
import { createUser, deleteUser, listUsers, updateUser, type ManagedUser, type UserForm } from '@/api/users'
import type { UserRole } from '@/api/auth'
import ModalDialog from './ModalDialog.vue'
import ToastMessage from './ToastMessage.vue'

type UserSortField = 'username' | 'displayName' | 'role' | 'department'
const users = ref<ManagedUser[]>([]); const dialogOpen = ref(false); const editing = ref<ManagedUser | null>(null); const error = ref(''); const sortBy = ref<UserSortField>('username'); const direction = ref<'asc' | 'desc'>('asc'); const page = ref(1); const pageSize = ref(10); const form = ref<UserForm>({ username: '', password: '', displayName: '', role: 'DEVICE_USER', department: '' }); const toast = ref({ visible: false, type: 'success' as 'success' | 'error', message: '' })
const roles: Array<{ value: UserRole; label: string }> = [{ value: 'SYSTEM_ADMIN', label: '系统管理员' }, { value: 'ADMIN', label: '管理员' }, { value: 'PRODUCTION_MANAGER', label: '生产部门管理者' }, { value: 'DEVICE_MANAGER', label: '设备部门管理者' }, { value: 'PRODUCTION_USER', label: '生产部门普通用户' }, { value: 'DEVICE_USER', label: '设备部门普通用户' }]
const pageSizeItems = [{ label: '10 条 / 页', value: 10 }, { label: '20 条 / 页', value: 20 }, { label: '50 条 / 页', value: 50 }]
const roleLabel = (role: UserRole): string => roles.find((item) => item.value === role)?.label ?? role
const sortedUsers = computed(() => [...users.value].sort((a, b) => { const result = String(a[sortBy.value] ?? '').localeCompare(String(b[sortBy.value] ?? ''), 'zh-CN', { numeric: true }); return direction.value === 'asc' ? result : -result }))
const pagedUsers = computed(() => sortedUsers.value.slice((page.value - 1) * pageSize.value, page.value * pageSize.value))
const columns: TableColumn<ManagedUser>[] = [{ accessorKey: 'username', header: () => sortHeader('username', '用户名') }, { accessorKey: 'displayName', header: () => sortHeader('displayName', '显示名称') }, { accessorKey: 'role', header: () => sortHeader('role', '角色') }, { accessorKey: 'department', header: () => sortHeader('department', '部门') }, { id: 'actions', header: '操作' }]
function sortHeader(field: UserSortField, label: string): ReturnType<typeof h> { return h(UButton, { variant: 'ghost', color: 'neutral', size: 'xs', label, onClick: () => sortByColumn(field) }) }
function sortByColumn(field: UserSortField): void { if (sortBy.value === field) direction.value = direction.value === 'asc' ? 'desc' : 'asc'; else { sortBy.value = field; direction.value = 'asc' }; page.value = 1 }
async function load(): Promise<void> { try { users.value = await listUsers(); page.value = 1 } catch { error.value = '用户数据加载失败' } }
function openCreate(): void { editing.value = null; form.value = { username: '', password: '', displayName: '', role: 'DEVICE_USER', department: '' }; dialogOpen.value = true }
function openEdit(user: ManagedUser): void { editing.value = user; form.value = { username: user.username, password: '', displayName: user.displayName, role: user.role, department: user.department ?? '' }; dialogOpen.value = true }
function closeDialog(): void { dialogOpen.value = false; editing.value = null }
async function save(): Promise<void> { const isEditing = Boolean(editing.value); try { if (editing.value) await updateUser(editing.value.id, form.value); else await createUser(form.value); closeDialog(); await load(); toast.value = { visible: true, type: 'success', message: isEditing ? '用户修改成功' : '用户创建成功' } } catch { toast.value = { visible: true, type: 'error', message: isEditing ? '用户修改失败' : '用户创建失败' } } }
async function remove(user: ManagedUser): Promise<void> { if (!window.confirm(`确定删除用户 ${user.displayName} 吗？`)) return; try { await deleteUser(user.id); await load(); toast.value = { visible: true, type: 'success', message: '用户删除成功' } } catch { toast.value = { visible: true, type: 'error', message: '用户删除失败' } } }
function changePageSize(value: number): void { pageSize.value = value; page.value = 1 }
onMounted(() => void load())
</script>

<template><div class="space-y-6"><ToastMessage :visible="toast.visible" :type="toast.type" :message="toast.message" @close="toast.visible = false" /><div class="flex items-end justify-between gap-4"><div><h2 class="text-xl font-bold text-highlighted">用户管理</h2><p class="mt-1 text-sm text-muted">维护账号、角色和部门信息。</p></div><UButton color="success" variant="solid" @click="openCreate">新增用户</UButton></div><UAlert v-if="error" color="error" variant="soft" :title="error" /><UCard><UTable :data="pagedUsers" :columns="columns" empty="暂无用户"><template #role-cell="{ row }"><UBadge color="primary" variant="subtle">{{ roleLabel(row.original.role) }}</UBadge></template><template #department-cell="{ row }"><span>{{ row.original.department || '-' }}</span></template><template #actions-cell="{ row }"><div class="flex justify-end gap-2"><UButton size="xs" variant="soft" @click="openEdit(row.original)">编辑</UButton><UButton size="xs" color="error" variant="soft" @click="remove(row.original)">删除</UButton></div></template></UTable><div class="mt-5 flex flex-wrap items-center justify-between gap-4 border-t border-default pt-4"><div class="flex items-center gap-2 text-sm text-muted"><span>每页显示</span><USelect :model-value="pageSize" :items="pageSizeItems" value-key="value" class="w-32" @update:model-value="changePageSize" /><span>共 {{ sortedUsers.length }} 条</span></div><UPagination v-if="sortedUsers.length > pageSize" v-model:page="page" :total="sortedUsers.length" :items-per-page="pageSize" /></div></UCard><ModalDialog :open="dialogOpen" :title="editing ? '编辑用户' : '新增用户'" @close="closeDialog"><form class="space-y-4" @submit.prevent="save"><UFormField label="用户名" required><UInput v-model="form.username" :disabled="Boolean(editing)" class="w-full" /></UFormField><UFormField label="密码" :required="!editing"><UInput v-model="form.password" type="password" placeholder="编辑时留空表示不修改" class="w-full" /></UFormField><UFormField label="显示名称" required><UInput v-model="form.displayName" class="w-full" /></UFormField><UFormField label="角色" required><USelect v-model="form.role" :items="roles" value-key="value" class="w-full" /></UFormField><UFormField label="部门"><UInput v-model="form.department" class="w-full" /></UFormField><div class="flex justify-end gap-3"><UButton type="button" variant="outline" color="neutral" @click="closeDialog">取消</UButton><UButton type="submit" variant="solid">保存</UButton></div></form></ModalDialog></div></template>
